#!/bin/bash
# Builds a double-clickable "Setlist Builder.app" launcher in
# ~/Applications, so you never have to open Terminal for day-to-day use.
#
# Run it once, from anywhere, with the venv already set up (see
# SETUP.md):
#     bash scripts/build_launcher.sh
#
# It's just a thin wrapper: double-clicking it runs the same
# `venv/bin/python3 main.py` you'd type by hand, using an absolute path
# to this project folder -- it doesn't bundle Python or copy any code,
# so it keeps working as long as this project folder stays where it is.

set -e

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$HOME/Applications/Setlist Builder.app"

if [ ! -x "$PROJECT_DIR/venv/bin/python3" ]; then
    echo "No venv found at $PROJECT_DIR/venv -- set that up first (see SETUP.md step 2), then run this again."
    exit 1
fi

mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"

cat > "$APP_DIR/Contents/MacOS/SetlistBuilder" <<EOF
#!/bin/bash
# Auto-generated by scripts/build_launcher.sh -- re-run that script if
# this project folder ever moves, rather than editing this by hand.
cd "$PROJECT_DIR"
LOG_DIR="\$HOME/Library/Logs/SetlistBuilder"
mkdir -p "\$LOG_DIR"
exec "$PROJECT_DIR/venv/bin/python3" main.py >> "\$LOG_DIR/launcher.log" 2>&1
EOF
chmod +x "$APP_DIR/Contents/MacOS/SetlistBuilder"

cat > "$APP_DIR/Contents/Info.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>Setlist Builder</string>
    <key>CFBundleDisplayName</key>
    <string>Setlist Builder</string>
    <key>CFBundleIdentifier</key>
    <string>com.setlistbuilder.launcher</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleExecutable</key>
    <string>SetlistBuilder</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSMinimumSystemVersion</key>
    <string>11.0</string>
</dict>
</plist>
EOF

# Best-effort custom icon, cropped from resources/cassette_asset.png --
# skipped silently (the app still works fine with a generic icon) if
# the venv's Pillow or macOS's own icon tools aren't available.
if [ -f "$PROJECT_DIR/resources/cassette_asset.png" ] && command -v iconutil >/dev/null && command -v sips >/dev/null; then
    ICON_TMP="$(mktemp -d)"
    "$PROJECT_DIR/venv/bin/python3" - "$PROJECT_DIR/resources/cassette_asset.png" "$ICON_TMP/base.png" <<'PY' || true
import sys
from PIL import Image
src, dest = sys.argv[1], sys.argv[2]
img = Image.open(src).convert("RGBA")
w, h = img.size
left = (w - h) // 2
img.crop((left, 0, left + h, h)).resize((1024, 1024)).save(dest)
PY
    if [ -f "$ICON_TMP/base.png" ]; then
        mkdir -p "$ICON_TMP/AppIcon.iconset"
        for size in 16 32 64 128 256 512; do
            sips -z "$size" "$size" "$ICON_TMP/base.png" --out "$ICON_TMP/AppIcon.iconset/icon_${size}x${size}.png" >/dev/null
            double=$((size * 2))
            sips -z "$double" "$double" "$ICON_TMP/base.png" --out "$ICON_TMP/AppIcon.iconset/icon_${size}x${size}@2x.png" >/dev/null
        done
        iconutil -c icns "$ICON_TMP/AppIcon.iconset" -o "$APP_DIR/Contents/Resources/AppIcon.icns" 2>/dev/null || true
    fi
    rm -rf "$ICON_TMP"
fi

touch "$APP_DIR"
echo "Built: $APP_DIR"
echo "Find it in Finder under your personal Applications folder, or drag it to the Dock."
