"""
Square, icon-only buttons for the Match/Add/Remove/Download/Merge
actions shared by ChartsPage, YouTubePage, and ReviewPage.

The icon files themselves (resources/icons/*.png) are pre-generated by
scripts/generate_icons.py, not drawn at runtime -- see that script to
regenerate one at a different size/color/stroke weight.
"""

from __future__ import annotations

from PySide6.QtCore import QSize, Qt
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import QPushButton, QWidget

from app.ui.assets import RESOURCES_DIR

# Every icon button shares this one fixed size -- per design decision,
# Match/Add/Remove/Download/Merge should all read as one consistent
# family of square buttons, not differently-sized text buttons.
ICON_BUTTON_SIZE = 34


def make_icon_button(
    icon_name: str, tooltip: str, parent: QWidget | None = None, size: int = ICON_BUTTON_SIZE
) -> QPushButton:
    """
    A square, icon-only QPushButton (no text label) -- `icon_name` must
    match one of resources/icons/{icon_name}.png. Since there's no text
    to explain what the button does once the icon replaces it, `tooltip`
    is required, not optional.

    `size` defaults to the shared ICON_BUTTON_SIZE (Match/Add/Remove/
    Download/Merge all read as one consistent family) -- pass a smaller
    value for a button that needs to fit into a tighter space, like the
    monthly carousel's Previous/Next corners.

    Sets BOTH the tooltip (a sighted hover hint) and the accessible name
    (what VoiceOver/screen readers actually announce -- not guaranteed
    to fall back to the tooltip text on every platform) from the same
    string, since an icon-only button has no visible text for either to
    fall back to.
    """
    if not tooltip:
        raise ValueError(f"make_icon_button({icon_name!r}, ...) needs a non-empty tooltip -- there's no button text for accessibility tools to fall back to.")

    button = QPushButton(parent)
    icon_path = RESOURCES_DIR / "icons" / f"{icon_name}.png"
    button.setIcon(QIcon(str(icon_path)))
    button.setIconSize(QSize(round(size * 0.6), round(size * 0.6)))
    button.setFixedSize(size, size)
    button.setToolTip(tooltip)
    button.setAccessibleName(tooltip)
    button.setCursor(Qt.PointingHandCursor)
    return button
